### ISSUE TITLE
Deployed but it seems to be getting a 500 error

### ISSUE THREAD

**Issue by aarongustafson** [billbogaiv/chronopanel#1]
https://chronopanel-10kapart2016.azurewebsites.net/?BackgroundColor=000000&HoursActiveColor=ff0000&HoursInactiveColor=701010&MinutesActiveColor=00ff00&MinutesInactiveColor=107010&SecondsActiveColor=0000ff&SecondsInactiveColor=101070

**Comment by billbogaiv** [comment]
@aarongustafson: should be good to go with https://github.com/billbogaiv/chronopanel/commit/4403a3c77bf54a85fdedb479189c14ed11ce310b.

**Comment by billbogaiv** [comment]
Confirmed the submission is working and active: https://a-k-apart.com/gallery/Chronopanel
